import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { TanstackProvider } from "@/components/providers/TanstackProvider"
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { AccessibilityProvider } from "@/contexts/accessibility-context";
import { AccessibilityWidget } from "@/components/shared/AccessibilityWidget";
const geistSans = Inter({ subsets: ["latin"], variable: "--font-geist-sans" });
const geistMono = Inter({ subsets: ["latin"], variable: "--font-geist-mono" });

export const metadata: Metadata = {
  title: "Yoshlar Parlamenti",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AccessibilityProvider>
          <NextIntlClientProvider messages={messages}>
            <TanstackProvider>
              <Header />
              <AccessibilityWidget />
              {children}
              <Footer />
            </TanstackProvider>
          </NextIntlClientProvider>
        </AccessibilityProvider>
      </body>
    </html>
  );
}
